export class PortfolioPositionDto {
  constructor(
      // public id: number,
      public symbol: string,
      public stockExchange: string,
      public name: string,
      public currency: string,
      public marketPricePerShare: number,
      public annualDividendRate: number,
      public earningPerShare: number,
      public returnOnEquity: number,
      public preisEarningRatio: number,
      public fiveYearIncomeGrowth: number,
      public fiveYearRevenueGrowth: number,
      public fiveYearDividendGrowth: number,
      public yild: number,
      public sector: string,
      public industry: string,
      public marketPricePerShareChange: number,
      public totalNumberOfShares: number,
      public averagePricePerShare: number,
      public totalCosts: number,
      public totalCostsMinusDividends: number,
      public adjustedAveragePricePerShare: number,
      public yieldOnCost: number,
      public marketValue: number,
      public yieldOnMarketValue: number,
      public weightOfPortfolio: number,
      public yieldTrailingOnMarketValue: number,
      public yieldForwardOnMarketValue: number,
      public yieldTrailingOnCost: number,
      public yieldForwardOnCost: number,
      public annualDividendRateTrailing: number,
      public annualDividendRateForward: number,
      public returnOnInvest: number,
      public totalEarnings: number,
      public marketDifference: number,
      public totalGrowthValue: number,
      public totalGrowth: number,
      public payoutRatio: number,
      public annualDividendForward: number,
      public annualDividends: number,
      public marketDifferenceValue: number,
      public currencyCode: string
  ) {}
}
